version: 3

tasks:
  install:
    desc: Install
    cmds:
      - pnpm install && pnpm prune

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm run build

  test:
    desc: Test
    deps: [ install ]
    cmds:
      - pnpm run test

  generateTestData:
    desc: Generate test data
    cmds:
      - ./gradlew copyTestData

  site-build:
    desc: Build site
    cmds:
      - task: site-clean
      - mkdir -p build/gh-pages
      - task: site-build-mdbook
      - task: site-build-typedoc
      - mkdir -p build/gh-pages/examples
      - cp src/test/test.html build/gh-pages/examples/

  site-clean:
    desc: Clean site
    cmds:
      - rm -rf build/gh-pages

  site-deploy:
    desc: Deploy site
    cmds:
      - gh-pages -d build/gh-pages --nojekyll

  site-build-typedoc:
    desc: Generate typedoc
    cmds:
      - pnpm run typedoc

  site-build-mdbook:
    desc: Generate mdbook
    cmds:
      - mdbook build --dest-dir $(pwd)/build/gh-pages src/main/mdbook

  mdbook-serve:
    desc: Serve mdbook
    dir: src/main/mdbook
    cmds:
      - mdbook serve

  build-example:
    desc: Build example
    dir: examples/svelte
    cmds:
      - pnpm install
      - pnpm run build

  run-example:
    desc: Build example
    dir: examples/svelte
    cmds:
      - pnpm install
      - pnpm run dev
