version: 3

tasks:
  install:
    desc: Install
    cmds:
      - pnpm install && pnpm prune

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm run build

  test:
    desc: Test
    deps: [ install ]
    cmds:
      - pnpm run test

  generateTestData:
    desc: Generate test data
    cmds:
      - ./gradlew copyTestData
